Feat/add google greenhouse
TheBlick/blick-scrapper pull request #5
Opened 2024-05-07 12:09 UTC by gabryuri

2024-05-12 18:18 UTC, Victor-Buendia requested changes
Cara, muito bom seu código! Tá muito organizado e bem estruturado. Arrasou.

🎉

2024-05-12 18:18 UTC, Victor-Buendia commented on src/db/db_config.py
>          return conn_string
Remover, porque você já criou a
```python
@property
    def database_uri(self) -> str:
        """
        Database URI to be used in SQLAlchemy.
        """
        return f"postgresql+psycopg2://{self.__db_username}:{self.__db_password}@{self.__db_host}:{self.__db_port}/{self.__db_name}"
```

2024-05-12 18:18 UTC, Victor-Buendia commented on src/db/db_config.py
> +        # self.__logger("creating all tables")
Remover ou descomentar

2024-05-12 18:18 UTC, Victor-Buendia commented on src/db/db_config.py
> +        self.__execute_stmt(insert_stmt)
Aqui você tá executando sempre o `insert_stmt`, deveria ser o `conflict_stmt`.

2024-05-12 18:18 UTC, Victor-Buendia commented on src/db/db_config.py
> +                # grabbing the schema from the first value: this demands that we declare null values explicitly
Ajeitar isso também. Acha que mudar a assinatura da função já faz essa verificação?
```python
def insert_data_to_rdbms(self, table, values_to_insert: list[dict], conflict_mode='upsert'):
```

2024-05-12 18:18 UTC, Victor-Buendia commented on src/db/db_config.py
> +                # grabbing the schema from the first value: this demands that we declare null values explicitly
`values_to_insert: list[dict]`

2024-05-12 18:18 UTC, Victor-Buendia commented on src/find_jobs.py
> +import json
Remover pois não está sendo usado

2024-05-12 18:18 UTC, Victor-Buendia commented on src/find_jobs.py
> +from dotenv import load_dotenv
Adicionar no requirements.txt

Acho que se for só pra testes locais, vale criar um `requirements.dev.txt` e um `requirements.txt` pra prod.

2024-05-12 18:18 UTC, Victor-Buendia commented on src/search_engines/google/google.py
> +import json
Remover pois não está usando

2024-05-12 18:18 UTC, Victor-Buendia commented on src/search_engines/google/google.py
> +        return url_list
Só está sendo usado aqui internamente na classe. Às vezes vale a pena por como privado `__get_urls`

2024-05-12 18:18 UTC, Victor-Buendia commented on src/search_engines/google/google.py
> +        self.cse_id = cse_id
Ocultar esses dados sensíveis

```suggestion
        self.__api_key = api_key
        self.__cse_id = cse_id
```

2024-05-12 18:18 UTC, Victor-Buendia commented on src/targets/greenhouse/constants.py
> +EMBED_JOB_REGEX_PATTERN = r"https://boards.greenhouse.io/embed/job_board\?for=([^\&\s]+)"
no passado acho que seria EMBEDDED

2024-05-12 18:18 UTC, Victor-Buendia commented on src/targets/greenhouse/greenhouse_job_board_parser.py
> +        self.job_url_pattern = re.compile(r"(/jobs/\d+)|(\?gh_jid=\d+)")
Não seria melhor por `r"(/jobs/\d+)|(\?gh_jid=\d+)"` em `constants.py`?

2024-05-12 18:18 UTC, Victor-Buendia commented on src/targets/greenhouse/greenhouse_job_board_parser.py
> +            self.__logger.info(f"Failed to retrieve the webpage: Status code {response.status_code}")
O log aqui é de info ou error?

2024-05-12 18:18 UTC, Victor-Buendia commented on src/targets/greenhouse/greenhouse_job_board_parser.py
> +            self.__logger.info(f"Failed to retrieve the webpage: Status code {response.status_code}")
Info ou error?

2024-05-12 18:18 UTC, Victor-Buendia commented on src/targets/greenhouse/greenhouse_url_classifier.py
> +from misc.utils import strip_non_numeric
Remover pois não tá sendo usado

2024-05-12 18:18 UTC, Victor-Buendia commented on src/targets/greenhouse/greenhouse_url_classifier.py
> +        return False
Tenho a impressão de que essa função ficaria melhor em `misc.py`

2024-05-12 18:18 UTC, Victor-Buendia commented on src/targets/greenhouse/greenhouse_url_classifier.py
> +        #TODO Add another step to add job postings inside the job boards
Cria uma issue pra isso por favor?

2024-05-12 18:18 UTC, Victor-Buendia commented on src/targets/greenhouse/greenhouse_url_classifier.py
> +            #     for job_board_url in self.job_board_parser.extract_embedded_job_info(url):
Remover se não for usar

2024-05-12 18:18 UTC, Victor-Buendia commented on src/targets/greenhouse/greenhouse_url_classifier.py
> +                classification_list.append(model.dict())
Tem como um job ter JobPosting e JobPostingFromBoard ao mesmo tempo? Se não for possível, acho que pode por um elif em vez de dois ifs.

```suggestion
            if self.__match_url_to_category(url=url, pattern=JOB_BOARD_REGEX_PATTERN):
                for job_board_dict in self.job_board_parser.extract_greenhouse_job_info(url):
                    model = JobPostingFromBoard(url=job_board_dict.get('url'), origin_url=url, title=job_board_dict.get('title'), location=job_board_dict.get('location'))
                    classification_list.append(model.dict())

             elif self.__match_url_to_category(url=url, pattern=JOB_POSTING_REGEX_PATTERN):
                model = JobPosting(url=url)
                classification_list.append(model.dict())
```

2024-05-12 18:18 UTC, Victor-Buendia commented on src/targets/greenhouse/models.py
> +from pydantic import BaseModel, validator
validator não tá sendo usado

2024-05-12 18:18 UTC, Victor-Buendia commented on src/targets/greenhouse/models.py
> +from typing import Optional
não tá sendo usado, remover

2024-05-12 18:18 UTC, Victor-Buendia commented on src/targets/greenhouse/models.py
> +                'title': None, #TODO - add something to make this schema generic to all models
Cria uma issue por favor?

2024-05-12 18:18 UTC, Victor-Buendia commented on src/tests/targets/greenhouse/test_greenhouse_job_board_parser.py
> +import requests
não tá sendo usado

2024-05-12 18:18 UTC, Victor-Buendia commented on src/tests/targets/greenhouse/test_greenhouse_job_board_parser.py
> +        parser = GreenhouseBoardParser(self.logger)
Por que ele é declarado aqui e na linha 12 também?

2024-05-12 18:18 UTC, Victor-Buendia commented on src/tests/targets/greenhouse/test_greenhouse_url_classifier.py
> +import json
Não tá sendo usado

2024-05-12 18:18 UTC, Victor-Buendia commented on src/tests/targets/greenhouse/test_greenhouse_url_classifier.py
> +from pydantic import BaseModel
Não tá sendo usado

2024-05-14 20:51 UTC, gabryuri commented on src/db/db_config.py
> +                # grabbing the schema from the first value: this demands that we declare null values explicitly
Na real isso é dentro de cada elemento. 
Tipo, todos os elementos dessa lista precisam ter explicito todos os valores de colunas, pra ele poder inferir o schema do primeiro registro. 

Imagina uma lista que tenha dois elementos com schemas diferentes: 

```
[
{'id': 1, 'col1': 'aaa'},
 {'id': 2, 'col1': 'bbb', 'col2': 'cccc'}
]
```

Segundo essa lógica, o schema q ele vai usar pro SQL vai ser o do 1o elemento, ou seja a gente precisaria ter um 'col2': None ali no primeiro elemento

2024-05-14 20:52 UTC, gabryuri commented on src/db/db_config.py
> +                # grabbing the schema from the first value: this demands that we declare null values explicitly
Vou deixar assim por hora, a gente deixa isso pro futuro, pq é mais delicado pegar o schema mais abrangente ou tornar a funcao mais atomica, pq a ideia é fazer em batches. Vou garantir esse schema usando os modelos do pydantic

2024-05-14 21:05 UTC, gabryuri commented on src/targets/greenhouse/models.py
> +                'title': None, #TODO - add something to make this schema generic to all models
Farei!

2024-05-14 21:10 UTC, gabryuri commented on src/targets/greenhouse/models.py
> +                'title': None, #TODO - add something to make this schema generic to all models
Done! https://github.com/TheBlick/blick-scrapper/issues/6

2024-05-14 21:47 UTC, merged